spring.datasource.url=jdbc:postgresql://localhost:5432/train_ticket_db
spring.datasource.username=train_ticket
spring.datasource.password=train_ticket
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=false

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
